# Generated by Django 5.2.1 on 2025-05-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=255, unique=True)),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('student_id_photo', models.ImageField(upload_to='student/photos')),
            ],
        ),
    ]
