# Generated by Django 5.2.1 on 2025-05-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='PendingUser',
        ),
    ]
