# Generated by Django 5.2.1 on 2025-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='email',
            field=models.CharField(default='example1@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
