# Generated by Django 5.2.1 on 2025-05-27 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useractivitylog_remove_verifieduser_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWalletInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletaddress', models.CharField(max_length=255, unique=True)),
                ('creditscore', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.verifieduser', to_field='student_id')),
            ],
        ),
    ]
