# Generated by Django 5.2.1 on 2025-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_loanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwalletinfo',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='userwalletinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
